name: Build Preview Deployment

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build-preview:
    if: ${{ github.repository == 'ilikui/NotesBook' }}
    runs-on: ubuntu-latest
    name: Build Preview
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - name: Check package.json scripts
        run: |
          echo "package.json 中的脚本:"
          node -e "console.log(JSON.stringify(require('./package.json').scripts, null, 2))"

      - name: Format code with Prettier
        run: npx prettier --write .

      - name: Check types and style
        run: npm run check

      - name: Build Quartz (尝试多种方法)
        run: |
          # 方法 1: 使用 package.json 中的构建脚本
          echo "尝试方法 1: 使用 npm run build..."
          npm run build && exit 0
          
          # 方法 2: 编译 TypeScript 然后运行
          echo "方法 1 失败，尝试方法 2: 编译 TypeScript..."
          npx tsc
          node quartz/build.js -d content -v && exit 0
          
          # 方法 3: 尝试直接运行 bootstrap 文件
          echo "方法 2 失败，尝试方法 3: 运行 bootstrap 文件..."
          node quartz/bootstrap-cli.mjs build -d content -v && exit 0
          
          # 方法 4: 尝试使用 npx 和本地 Quartz
          echo "方法 3 失败，尝试方法 4: 使用 npx 和本地 Quartz..."
          npx --prefix . quartz build -d content -v && exit 0
          
          echo "所有构建方法都失败了!"
          exit 1

      - name: Verify build output
        run: |
          echo "构建输出内容:"
          ls -la public/ || echo "public 目录不存在"
          find public/ -type f | head -10 || true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: public-build
          path: public