name: Build Preview Deployment

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build-preview:
    if: ${{ github.repository == 'ilikui/NotesBook' }}
    runs-on: ubuntu-latest
    name: Build Preview
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x' # 指定使用 Node.js 22.x
          cache: 'npm'

      - name: Verify Node and npm versions
        run: |
          echo "Node.js version: $(node -v)"
          echo "npm version: $(npm -v)"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - name: Dependency
        run: npm install

      - name: Fix execution permissions
        run: |
          echo "修复执行权限..."
          chmod -R +x node_modules/.bin/
          find . -name "quartz" -type f -exec chmod +x {} \; || true
          echo "权限修复完成"

      - name: Format code with Prettier
        run: npx prettier --write .

      - name: Check types and style
        run: npm run check

      - name: Build Quartz
        run: |
          # 尝试多种方式运行 quartz
          echo "尝试运行 quartz 构建..."
          if [ -f "node_modules/.bin/quartz" ]; then
            echo "使用本地安装的 quartz..."
            ./node_modules/.bin/quartz build -d content -v
          else
            echo "使用 npx 运行 quartz..."
            npx quartz build -d content -v
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: public-build
          path: public