name: Deploy Quartz site to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'gh-pages'
  push:
    branches: [ main ]

permissions:
  pages: write
  id-token: write
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  discussions: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4  # 更新到最新版本
        with:
          fetch-depth: 0 # Fetch all history for git info
          
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'  # 更改为 Node.js 22
          cache: 'npm'  # 添加缓存加速构建
          
      - name: Check versions
        run: |
          node --version
          npm --version
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build Quartz
        run: npx quartz build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # 使用稳定版本
        with:
          path: public

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3  # 更新到最新版本